### ISSUE TITLE
arga与argb的输入

### ISSUE THREAD

**Issue by carrie0307** [megemini/-_megemini-#3]
您好，请问您能举例说一下arga和argb在[这里](https://github.com/megemini/-_megemini-/blob/2144a8acec17450a4d5adcb22fd65a1525fd7b0c/run.py#L763)输入时具体的数据形式吗？或者，您可以将run.ipynb也发布吗？

因为没有数据这个地方不太理解，麻烦您啦！谢谢啦！

**Comment by megemini** [comment]
当时是在阿里的pai平台上面运行的，没法下载ipynb，只能导出html......

`hist_1 = model.fit(x=[train_x_text_list[:, ::-1], train_x_arga_list[:, ::-1], train_x_argb_list[:, ::-1]], y=train_y_list[:, ::-1, :],
`

这里是将arga和argb的编码反序后作为输入，如果能够理解arga和argb的具体表示，比如arga编码后为：001112200，那么这儿就是：002211100，argb同理，其实text更好理解，就是反话：阿森纳是冠军，那么这儿就是：军冠是纳森阿...

**Comment by carrie0307** [comment]
好的，谢谢啦~
