### ISSUE TITLE
滑窗步长问题

### ISSUE THREAD

**Issue by s192516** [megemini/-_megemini-#4]
您好,我是小白,看到您说明里在第二轮比赛中,滑窗的偏移量不是很理解,是步长的意思吗,
请问是否考虑过一个实体可能因为滑窗原因别切割如"尿病的临床表现为病人持续发烧.........."
前面"先天性糖尿病"这个实体因为被截断导致识别准确率下降这种情况?

**Comment by megemini** [comment]
1. 类似于步长，只不过这里是针对某一个实体，以此实体为中心点左右滑动，所以MARGIN_LIST有正有负。

2. 对于被截断的实体，标记为普通文本，也就是说，只有完整的实体才被标注并进行训练。至于识别准确率，由于被截断的实体一般为窗口的边缘部分，我们预测时可以只考虑窗口“中心”部分的成绩（参考正态分布），所以个人认为影响有限。

**Comment by s192516** [comment]
> 1. 类似于步长，只不过这里是针对某一个实体，以此实体为中心点左右滑动，所以MARGIN_LIST有正有负。
> 2. 对于被截断的实体，标记为普通文本，也就是说，只有完整的实体才被标注并进行训练。至于识别准确率，由于被截断的实体一般为窗口的边缘部分，我们预测时可以只考虑窗口“中心”部分的成绩（参考正态分布），所以个人认为影响有限。

明白了,非常感谢
