### ISSUE TITLE
数据怎么划分的？

### ISSUE THREAD

**Issue by lunjiaqi** [megemini/-_megemini-#5]
你好，请问数据怎么划分的？
train_ann_file_list = glob('./Demo/DataSets/ruijin_round2_train/ruijin_round2_train/*.ann')
train_txt_file_list = glob('./Demo/DataSets/ruijin_round2_train/ruijin_round2_train/*.txt')
test_txt_file_list = glob('./Demo/DataSets/ruijin_round2_test_b/ruijin_round2_test_b/*.txt')
test_ann_file_list = glob('./Demo/DataSets/ruijin_round2_test_b/ruijin_round2_test_b/*.ann')
下载的数据有986个，请问训练集和测试集怎么划分的？谢谢!

**Comment by megemini** [comment]
训练集分为:训练和验证两部分
`    kf = KFold(n_splits=KFOLD, shuffle=True, random_state=522).split(data_x_text_list)
    train_idx, valid_idx = next(kf)
`
测试集应该是赛题给的吧~ 时间久了有点记得不是很清楚了...

**Comment by megemini** [comment]
长时间无回复关闭。

**Comment by lunjiaqi** [comment]
您好，你的邮件我收到了，谢谢!

**Comment by lunjiaqi** [comment]
您好，你的邮件我收到了，谢谢!
